### ISSUE TITLE
✨라우팅 구성 및 작업영역 분리 

### ISSUE THREAD

**Issue by jurilee0** [Dev-FE-2/toy-project1-team1-intranet-project#15]
## 라우팅 구성
라우팅 구성을 추가하고 담당자 별 작업 영역을 분리합니다.

## Todo
- [x] index.js 추가
- [x] 렌더링 방식 협의
- [x] js 파일 생성

## 기간
2024.10.21

**Comment by jurilee0** [comment]
**24.10.23 결정사항**
- 함수형 컴포넌트 활용
- feature/route 브랜치 병합 없이, 기존 markup 브랜치에서 구조 생성하여 main merge
- 10/24 오전 main 기준으로 작업자 브랜치 분리하여 기능 개발 착수
